sudo: required

language: go
go: 1.8

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
  - docker pull blacktop/elasticsearch
  - sudo sysctl -w vm.max_map_count=262144

install:
  - make setup
  - go build -o malice-travis

script:
  - make test
  - ./malice-travis -D elk
  - go test -race -coverprofile=coverage.txt -covermode=atomic  

after_success:
  - bash <(curl -s https://codecov.io/bash)
