language: go
sudo: required

services:
  - docker

go: 1.8

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
  - docker pull blacktop/elasticsearch

install:
  - make setup
  - gem install fpm

script:
  - make test
  - go build -o malice-travis
  - ./malice-travis elk

after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash main.go
