language: go
sudo: false
go:
  - 1.5.3
  - 1.6
  - tip

env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagic-dev

install: make deps
script:
  - make test
