sudo: required

language: go
go: 1.8

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version
  - docker pull blacktop/elasticsearch

install:
  - make setup

script:
  - make test
  - go build -o malice-travis
  - ./malice-travis -D elk

after_success:
  - bash <(curl -s https://codecov.io/bash)
