
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = ">=0.11.0, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/moby/moby"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  name = "github.com/spf13/cobra"
  source = "https://github.com/dnephin/cobra.git"
  version = "v1.5.1"

[[dependencies]]
  name = "github.com/spf13/pflag"
  revision = "9ff6c6923cfffbcd502984b8e0c80539a94968b7"

[[dependencies]]
  name = "golang.org/x/net"
  revision = "07b51741c1d6423d4a6abab1c49940ec09cb1aaf"
