
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = ">=0.11.0, <1.0.0"

[[dependencies]]
  name = "github.com/hashicorp/vault"
  version = "v0.7.1"

[[dependencies]]
  branch = "master"
  name = "github.com/moby/moby"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"

[[dependencies]]
  name = "golang.org/x/net"
  revision = "07b51741c1d6423d4a6abab1c49940ec09cb1aaf"
