# Copyright (c) 2013 - 2015 blacktop Joshua Maine, All Rights Reserved.
# See LICENSE for license information.

#######################################################################
# PLUGIN Configuration ################################################
#######################################################################

[[plugin]]
  name = "nsrl"
  enabled = false
  description = "NSRL Database Hash Search"
  category = "binary"
  image = "blacktop/nsrl"
  mime = "*"

[[plugin]]
  name = "fileinfo"
  enabled = false
  description = "ssdeep/exiftool/TRiD"
  category = "metadata"
  image = "malice/fileinfo"
  mime = "*"

[[plugin]]
  name = "clamav"
  enabled = true
  description = "ClamAV"
  category = "av"
  image = "malice/clamav"
  mime = "*"

[[plugin]]
  name = "fprot"
  enabled = true
  description = "F-PROT AntiVirus"
  category = "av"
  image = "malice/fprot"
  mime = "*"

[[plugin]]
  name = "pdfid"
  enabled = false
  description = "PDFiD - tool to triage PDF documents"
  category = "document"
  image = "blacktop/pdfid"
  mime = "application/pdf"
